ECHO OFF
 
SET  CLASSPATH_JAR=SVN_LOCAL\lib\static\junit\junit-4.12.jar;hamcrest-core-1.3.jar

SET  SRC_IMPLEMENTATION=SVN_LOCAL\implementation\src

SET  SRC_JUNIT=SVN_LOCAL\junit\src

SET    CLASS_TO_COMPILE_IMPLEMENTATION=%SRC_IMPLEMENTATION%\name\nameinitials\NameInitials.java

SET CLASS_TO_COMPILE_JUNIT=%SRC_JUNIT%\name\nameinitials\InitialsTestCase.java

SET BUILD_CLASS_DIR_IMPLEMENTATION=BUILD_LOCAL\implementation\build\classes

SET BUILD_CLASS_DIR_JUNIT=BUILD_LOCAL\junit\build\classes

ECHO CLASSPATH_JAR=%CLASSPATH_JAR%

ECHO SRC_IMPLEMENTATION=%SRC_IMPLEMENTATION%

ECHO SRC_JUNIT=%SRC_JUNIT%

ECHO CLASS_TO_COMPILE_IMPLEMETATION=%CLASS_TO_COMPILE_IMPLEMENTATION%

ECHO CLASS_TO_COMPILE_JUNIT=%CLASS_TO_COMPILE_JUNIT%

ECHO BUILD_CLASS_DIR_IMPLEMENTATION=%BUILD_CLASS_DIR_IMPLEMENTATION%

ECHO BUILD_CLASS_DIR_JUNIT=%BUILD_CLASS_DIR_JUNIT%

javac -sourcepath %SRC_IMPLEMENTATION% -cp %CLASSPATH_JAR% -d %BUILD_CLASS_DIR_IMPLEMENTATION% %CLASS_TO_COMPILE_IMPLEMENTATION%

javac -sourcepath %SRC_IMPLEMENTATION% -cp %CLASSPATH_JAR%;%BUILD_CLASS_DIR_IMPLEMENTATION%  -d %BUILD_CLASS_DIR_JUNIT% %CLASS_TO_COMPILE_JUNIT%  

PAUSE




